package com.pichincha.money.util;

public enum CurrencyType {
    
    AED("Dirham de los Emiratos Árabes Unidos"),
    AFN("Afgani afgano"),
    ALL("Lek albanés"),
    AMD("Dram armenio"),
    ANG("Florín de las Antillas Neerlandesas"),
    AOA("Kwanza angoleño"),
    ARS("Peso argentino"),
    AUD("Dólar australiano"),
    AWG("Florín arubeño"),
    AZN("Manat azerbaiyano"),
    BAM("Marco convertible de Bosnia-Herzegovina"),
    BBD("Dólar de Barbados"),
    BDT("Taka bangladesí"),
    BGN("Lev búlgaro"),
    BHD("Dinar bahreiní"),
    BIF("Franco burundés"),
    BMD("Dólar bermudeño"),
    BND("Dólar de Brunéi"),
    BOB("Boliviano"),
    BRL("Real brasileño"),
    BSD("Dólar bahameño"),
    BTC("Bitcoin"),
    BTN("Ngultrum butanés"),
    BWP("Pula botsuano"),
    BYN("Rublo bielorruso"),
    CAD("Dólar canadiense"),
    CHF("Franco suizo"),
    CLP("Peso chileno"),
    CNY("Yuan chino"),
    COP("Peso colombiano"),
    CRC("Colón costarricense"),
    CUP("Peso cubano"),
    CZK("Corona checa"),
    DKK("Corona danesa"),
    DOP("Peso dominicano"),
    DZD("Dinar argelino"),
    EGP("Libra egipcia"),
    ERN("Nakfa eritreo"),
    ETB("Birr etíope"),
    EUR("Euro"),
    FJD("Dólar fiyiano"),
    FKP("Libra de las Islas Malvinas"),
    GBP("Libra esterlina"),
    GEL("Lari georgiano"),
    GHS("Cedi ghanés"),
    GIP("Libra de Gibraltar"),
    GMD("Dalasi gambiano"),
    GTQ("Quetzal guatemalteco"),
    GYD("Dólar guyanés"),
    HKD("Dólar de Hong Kong"),
    HNL("Lempira hondureño"),
    HRK("Kuna croata"),
    HUF("Forinto húngaro"),
    IDR("Rupia indonesia"),
    ILS("Nuevo shéquel israelí"),
    INR("Rupia india"),
    IQD("Dinar iraquí"),
    IRR("Rial iraní"),
    ISK("Corona islandesa"),
    JMD("Dólar jamaicano"),
    JOD("Dinar jordano"),
    JPY("Yen japonés"),
    KES("Chelín keniano"),
    KGS("Som kirguís"),
    KHR("Riel camboyano"),
    KMF("Franco comorense"),
    KRW("Won surcoreano"),
    KWD("Dinar kuwaití"),
    KZT("Tenge kazajo"),
    LAK("Kip laosiano"),
    LBP("Libra libanesa"),
    LKR("Rupia de Sri Lanka"),
    LRD("Dólar liberiano"),
    LSL("Loti lesotense"),
    MAD("Dírham marroquí"),
    MDL("Leu moldavo"),
    MGA("Ariary malgache"),
    MKD("Denar macedonio"),
    MMK("Kyat birmano"),
    MNT("Tugrik mongol"),
    MOP("Pataca de Macao"),
    MRO("Ouguiya mauritano"),
    MUR("Rupia mauriciana"),
    MVR("Rufiyaa maldiva"),
    MWK("Kwacha malauí"),
    MXN("Peso mexicano"),
    MYR("Ringgit malayo"),
    MZN("Metical mozambiqueño"),
    NAD("Dólar namibio"),
    NGN("Naira nigeriano"),
    NOK("Corona noruega"),
    NPR("Rupia nepalí"),
    NZD("Dólar neozelandés"),
    OMR("Rial omaní"),
    PAB("Balboa panameño"),
    PEN("Sol peruano"),
    PGK("Kina de Papúa Nueva Guinea"),
    PHP("Peso filipino"),
    PKR("Rupia pakistaní"),
    PLN("Zloty polaco"),
    PYG("Guaraní paraguayo"),
    QAR("Riyal qatarí"),
    RON("Leu rumano"),
    RUB("Rublo ruso"),
    RWF("Franco ruandés"),
    SAR("Riyal saudí"),
    SDG("Libra sudanesa"),
    SEK("Corona sueca"),
    SGD("Dólar de Singapur"),
    SYP("Libra siria"),
    THB("Baht tailandés"),
    TJS("Somoni tayiko"),
    TMT("Manat turcomano"),
    TND("Dinar tunecino"),
    TRY("Lira turca"),
    TTD("Dólar de Trinidad y Tobago"),
    TWD("Nuevo dólar taiwanés"),
    TZS("Chelín tanzano"),
    UAH("Grivna ucraniana"),
    UGX("Chelín ugandés"),
    USD("Dólar estadounidense"),
    UYU("Peso uruguayo"),
    UZS("Som uzbeko"),
    VES("Bolívar venezolano"),
    VND("Dong vietnamita"),
    XAF("Franco CFA de África Central"),
    XCD("Dólar del Caribe Oriental"),
    XOF("Franco CFA de África Occidental"),
    XPF("Franco CFP"),
    YER("Rial yemení"),
    ZAR("Rand sudafricano"),
    ZMW("Kwacha zambiano");

    private final String description;

    CurrencyType(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }
}